"use client";
import {useEffect,useState} from 'react';
import {ArrowRight,CheckCircle2,FlaskConical,LockKeyhole,WalletCards} from 'lucide-react';
import type {CandidateFilter} from '@/lib/domain';
import type {Review} from './approval-center';
import type {Research as FullResearch} from './research-reader';
import {TradingResearchReader} from './trading-research-reader';

type Candidate={key:string;ticker:string;buyers:number;sellers:number;holders:number};
type Research=FullResearch&{ticker:string;action?:string;actionReason?:string;allocationScore?:number};
export type PipelineResult={runId:string;status:string;stage?:string;proposalStatus?:string;error?:string;candidateCount?:number;selectedCandidates:Candidate[];research?:Research[];currentCandidate?:{index:number;total:number;ticker:string;status?:string;progress?:{percent:number;current:string}};plan?:{period:string;accountSnapshot:{asOf:string;usdCashBuyingPower:string;usHoldingsValue:string;usCapitalUsd:string;protectedHoldingsValue:string;usHoldingCount:number;excludedKrHoldingCount:number;excludedAssets:{symbol?:string;marketCountry?:string;currency?:string;marketValue:string}[]};portfolio:{positions:{ticker:string;amount:number;weight:number;allocationScore:number}[];cashTarget:string;protectedHoldingsValue:string};research:Research[];excluded:{ticker:string;reason:string}[];orders:{symbol:string;side:string;quantity:string;price:string}[];proposalMessage?:string};review?:Review|null};

const money=(value:string|number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(value));
const actionLabel:Record<string,string>={buy:'매수 검토',sell:'매도 검토',hold:'유지'};
const pipelineStorageKey='hedge-active-pipeline-run-id';
const candidateCountStorageKey='hedge-pipeline-candidate-count';

export function PipelineWorkspace({fundIds,candidateFilter,onReview}:{fundIds:string[];candidateFilter:CandidateFilter;onReview:(review:Review|null)=>void}){
 const [runId,setRunId]=useState(''),[result,setResult]=useState<PipelineResult|null>(null),[error,setError]=useState(''),[readerTicker,setReaderTicker]=useState<string|null>(null),[candidateCount,setCandidateCount]=useState(()=>{try{const saved=Number(globalThis.localStorage?.getItem(candidateCountStorageKey));return Number.isInteger(saved)&&saved>=1&&saved<=8?saved:6}catch{return 6}});
 useEffect(()=>{let stopped=false;const restore=async()=>{try{const saved=localStorage.getItem(pipelineStorageKey);if(saved&&/^[a-f0-9]{32}$/.test(saved)){if(!stopped)setRunId(saved);return}}catch{}try{const response=await fetch('/api/pipeline?active=1',{cache:'no-store'});if(!response.ok)return;const next=await response.json() as PipelineResult;if(stopped)return;setResult(next);setRunId(next.runId);try{localStorage.setItem(pipelineStorageKey,next.runId)}catch{}}catch{}};void restore();return()=>{stopped=true}},[]);
 useEffect(()=>{if(!runId)return;let stopped=false;const poll=async()=>{try{const response=await fetch(`/api/pipeline?runId=${runId}`,{cache:'no-store'});const next=await response.json() as PipelineResult;if(!response.ok)throw Error(next.error||'상태 확인 실패');if(stopped)return;setError('');setResult(next);if(next.review)onReview(next.review);if(!['queued','running'].includes(next.status))return;timer=window.setTimeout(poll,2000)}catch(e){if(!stopped)setError(e instanceof Error?e.message:'상태 확인 실패')}};let timer=window.setTimeout(poll,100);return()=>{stopped=true;window.clearTimeout(timer)}},[runId,onReview]);
 async function start(){setError('');setResult(null);onReview(null);try{const response=await fetch('/api/pipeline',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fundIds,candidateFilter,candidateCount})});const next=await response.json() as PipelineResult;if(!response.ok)throw Error(next.error||'파이프라인 시작 실패');setResult(next);setRunId(next.runId);try{localStorage.setItem(pipelineStorageKey,next.runId);localStorage.setItem(candidateCountStorageKey,String(candidateCount))}catch{}}catch(e){setError(e instanceof Error?e.message:'파이프라인 시작 실패')}}
 const plan=result?.plan;
 const readerResult=readerTicker?result?.research?.find(report=>report.ticker===readerTicker):undefined;
 return <div className="pipeline-workspace"><TradingResearchReader result={readerResult} title={readerTicker||''} onClose={()=>setReaderTicker(null)}/><div className="research-intro"><div><p className="eyebrow">02 / RESEARCH TO PROPOSAL</p><h2>선택부터 매매안까지, 한 번에.</h2><p>선택한 수만큼 상위 후보를 조사하고 토스의 현재 미국 자산으로 승인 전 주문안을 만듭니다.</p></div><span className="subtle-badge">주문 자동 전송 없음</span></div>
 <div className="pipeline-flow"><div><FlaskConical/><b>후보·리서치</b></div><ArrowRight/><div><WalletCards/><b>계좌 기반 배분</b></div><ArrowRight/><div><LockKeyhole/><b>승인 대기</b></div></div>
 <section className="panel pipeline-launch"><div><h2>선택 펀드 {fundIds.length}개</h2><p className="muted">같은 방향으로 움직인 펀드 수와 일치율 순으로 조사합니다. 국내주식과 원화는 매매안에서 제외합니다.</p></div><div className="candidate-controls"><label className="threshold-control">리서치 종목 수 <select aria-label="리서치 종목 수" value={candidateCount} disabled={result?.status==='queued'||result?.status==='running'} onChange={e=>setCandidateCount(Number(e.target.value))}>{Array.from({length:8},(_,i)=>i+1).map(n=><option key={n} value={n}>{n}개</option>)}</select></label><button className="primary-button" disabled={!fundIds.length||result?.status==='queued'||result?.status==='running'} onClick={start}>리서치하고 매매안 만들기</button></div></section>
 {error&&<p className="report-error" role="alert">{error}</p>}
 {result&&<section className="panel pipeline-run"><div className="section-heading"><div><p className="eyebrow">PIPELINE RUN</p><h2>{result.status==='completed'?'매매안 생성 완료':result.status==='failed'?'파이프라인 중단':'파이프라인 실행 중'}</h2></div><span className="subtle-badge">{result.stage||result.status}</span></div>
 <div className="pipeline-candidates">{result.selectedCandidates.map((c,index)=>{const report=result.research?.find(r=>r.ticker===c.ticker);const active=result.currentCandidate?.ticker===c.ticker;return <div key={c.key} data-state={report?'completed':active?'running':'pending'}><span>{index+1}</span><b>{c.ticker}</b><small>{report?.cacheHit?'동일 조건 캐시 재사용':`${Math.max(c.buyers,c.sellers)}개 펀드 같은 방향`}</small>{report?<><CheckCircle2/><button className="secondary-button" onClick={()=>setReaderTicker(c.ticker)}>리서치 전문</button></>:active?<em>{result.currentCandidate?.progress?.percent||0}%</em>:null}</div>})}</div>
 {result.currentCandidate&&result.status==='running'&&<p className="muted">{result.currentCandidate.index}/{result.currentCandidate.total} · {result.currentCandidate.ticker} {result.currentCandidate.progress?`${result.currentCandidate.progress.percent}%`:result.currentCandidate.status||'준비 중'}</p>}
 {result.error&&<p className="negative">{result.error}</p>}</section>}
 {plan&&<><section className="panel account-summary"><div className="section-heading"><h2>토스 미국자산 스냅샷</h2><span className="subtle-badge">{new Date(plan.accountSnapshot.asOf).toLocaleString('ko-KR')}</span></div><dl><div><dt>미국 투자 가능 자본</dt><dd>{money(plan.accountSnapshot.usCapitalUsd)}</dd></div><div><dt>USD 매수가능 현금</dt><dd>{money(plan.accountSnapshot.usdCashBuyingPower)}</dd></div><div><dt>미국주식 평가액</dt><dd>{money(plan.accountSnapshot.usHoldingsValue)}</dd></div><div><dt>보호 보유액</dt><dd>{money(plan.accountSnapshot.protectedHoldingsValue)}</dd></div></dl><p className="muted">제외 자산: {plan.accountSnapshot.excludedAssets.length?plan.accountSnapshot.excludedAssets.map(asset=>`${asset.symbol||'미확인'} ${asset.marketValue} ${asset.currency||''}`).join(' · '):'없음'} — 자본 계산·환전·주문 대상에 포함하지 않습니다.</p></section>
 <section className="panel"><div className="section-heading"><h2>TradingAgents 최종 판단</h2><span className="subtle-badge">{plan.period}</span></div><div className="proposal-grid">{plan.research.map(r=><article key={r.ticker} data-action={r.action}><div><b>{r.ticker}</b><span>{actionLabel[r.action||'hold']||r.action}</span></div><p>{r.decision?.thesis}</p><small>{r.actionReason}</small><small>최종 등급 {r.upstreamSignal} · 신호 강도 {r.decision?.score}/100 · 배분 점수 {r.allocationScore?.toFixed(2)}</small><button className="secondary-button" onClick={()=>setReaderTicker(r.ticker)}>리서치 전문 보기</button></article>)}</div></section>
 <section className="panel"><div className="section-heading"><h2>계좌 기반 목표와 주문안</h2><span className="subtle-badge">{result?.proposalStatus}</span></div>{plan.portfolio.positions.length?<div className="review-table"><table><thead><tr><th>종목</th><th>목표액</th><th>목표 비중</th><th>배분 점수</th></tr></thead><tbody>{plan.portfolio.positions.map(p=><tr key={p.ticker}><td>{p.ticker}</td><td>{money(p.amount)}</td><td>{(p.weight*100).toFixed(2)}%</td><td>{p.allocationScore.toFixed(2)}</td></tr>)}</tbody></table></div>:<p>검증 조건을 통과한 신규 목표가 없습니다.</p>}<p className="muted">목표 현금 {money(plan.portfolio.cashTarget)} · 보호 보유 {money(plan.portfolio.protectedHoldingsValue)}</p>{plan.proposalMessage&&<p className="negative">{plan.proposalMessage}</p>}{result?.review?<p className="positive">승인 보고서가 생성되었습니다. 승인 센터에서 검토하세요.</p>:<p className="muted">승인 가능한 주문이 없거나 최신 시세·미체결 주문 확인이 필요합니다.</p>}</section></>}
 </div>;
}
