"use client";
import {useEffect,useState} from 'react';
import {movementCounts,type Aggregate,type CandidateFilter} from '@/lib/domain';
import {riskPlan} from '@/lib/swing';
import {ResearchProgress,ResearchConclusion,type Research} from './research-reader';
type Entry={id:string;at:string;ticker:string;period:string;fundIds:string[];thesis:string;trigger:string;invalid:string;review:string;decision:string;researchAt?:string};
const storageKey='hedge-swing-journal-v1';
const number=(v:number|undefined|null,suffix='')=>v==null?'—':v.toFixed(2)+suffix;
export function SwingWorkspace({rows,candidateFilter,onFilter,onExportPolicy,fundIds,period,researchFor,onResearch,onRead,onEvidence,busy}:{rows:Aggregate[];candidateFilter:CandidateFilter;onFilter:(value:CandidateFilter)=>void;onExportPolicy:()=>void;fundIds:string[];period:string;researchFor:(r:Aggregate)=>Research|undefined;onResearch:(r:Aggregate)=>void;onRead:(r:Aggregate)=>void;onEvidence:(r:Aggregate)=>void;busy:boolean}){
 const [page,setPage]=useState(0),[message,setMessage]=useState('');
 const [chosen,setChosen]=useState(''),[journal,setJournal]=useState<Entry[]>([]),[thesis,setThesis]=useState(''),[trigger,setTrigger]=useState(''),[invalid,setInvalid]=useState(''),[review,setReview]=useState(''),[decision,setDecision]=useState('observe');
 const [entry,setEntry]=useState(''),[stop,setStop]=useState(''),[target,setTarget]=useState(''),[budget,setBudget]=useState('1000'),[risk,setRisk]=useState('10');
 const context=[...fundIds].sort().join(',')+'|'+period+'|'+JSON.stringify(candidateFilter);
 useEffect(()=>{const timer=window.setTimeout(()=>{setPage(0);setChosen('');setMessage('')},0);return()=>window.clearTimeout(timer)},[context]);
 useEffect(()=>{const timer=window.setTimeout(()=>{try{const saved=JSON.parse(localStorage.getItem(storageKey)||'[]');if(Array.isArray(saved)&&saved.every(e=>e&&typeof e.id==='string'&&typeof e.thesis==='string'&&typeof e.trigger==='string'&&typeof e.invalid==='string'&&typeof e.review==='string'&&typeof e.ticker==='string'&&typeof e.at==='string'))setJournal(saved);else setMessage('저장된 기록 형식을 읽을 수 없습니다.')}catch{setMessage('브라우저 기록을 읽지 못했습니다.')}},0);return()=>window.clearTimeout(timer)},[]);
 const pageCount=Math.max(1,Math.ceil(rows.length/8)),current=Math.min(page,pageCount-1),visible=rows.slice(current*8,current*8+8),selected=rows.find(r=>r.key===chosen),plan=riskPlan(+entry,+stop,+target,+budget,+risk);
 function save(){if(!selected||!thesis.trim()||!trigger.trim()||!invalid.trim()||!review)return;const item:Entry={id:crypto.randomUUID(),at:new Date().toISOString(),ticker:selected.ticker!,period,fundIds:[...fundIds],thesis,trigger,invalid,review,decision,researchAt:researchFor(selected)?.createdAt};const next=[item,...journal];try{localStorage.setItem(storageKey,JSON.stringify(next));setJournal(next);setMessage('판단 시점의 근거를 기록했습니다.');setThesis('');setTrigger('');setInvalid('')}catch{setMessage('저장 공간 또는 브라우저 권한 문제로 기록을 저장하지 못했습니다.')}}
 function deleteEntry(id:string){const next=journal.filter(item=>item.id!==id);try{localStorage.setItem(storageKey,JSON.stringify(next));setJournal(next);setMessage('판단 기록을 삭제했습니다.')}catch{setMessage('브라우저 저장소에 접근할 수 없어 삭제하지 못했습니다.')}}
 function exportJournal(){const url=URL.createObjectURL(new Blob([JSON.stringify({schemaVersion:1,entries:journal},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='swing-journal.json';a.click();URL.revokeObjectURL(url)}
 return <div className="swing-workspace"><div className="research-intro"><div><p className="eyebrow">01 / DISCOVER THE CHANGE</p><h2>이번 분기, 자금은 어디로 움직였을까.</h2><p>공통 신규·확대와 축소·청산에서 출발하는 투자 리서치.</p></div><span className="subtle-badge">{period} 기준</span></div>
 <div className="change-metrics"><div><span>리서치 후보</span><strong>{rows.length}<small> 종목</small></strong></div><div><span>공통 신규 · 확대</span><strong className="positive">{rows.filter(r=>r.buyers>=candidateFilter.minFunds).length}</strong></div><div><span>공통 축소 · 청산</span><strong className="negative">{rows.filter(r=>r.sellers>=candidateFilter.minFunds).length}</strong></div><div><span>확대 · 축소 의견 대립</span><strong>{rows.filter(r=>r.buyers>=candidateFilter.minFunds&&r.sellers>=candidateFilter.minFunds).length}</strong></div></div>
 <div className="candidate-controls"><div className="direction-tabs" aria-label="공통 변화 방향">{([['all','모든 변화'],['increase','신규 · 확대'],['decrease','축소 · 청산']] as const).map(([value,label])=><button key={value} aria-pressed={candidateFilter.direction===value} onClick={()=>onFilter({...candidateFilter,direction:value})}>{label}</button>)}</div><label className="threshold-control">같은 방향 최소 <select aria-label="최소 공통 펀드 수" value={candidateFilter.minFunds} onChange={e=>onFilter({...candidateFilter,minFunds:Number(e.target.value)})}>{Array.from({length:29},(_,i)=>i+2).map(n=><option key={n} value={n}>{n}개 펀드</option>)}</select></label><label className="mixed-control"><input type="checkbox" checked={candidateFilter.includeMixed} onChange={e=>onFilter({...candidateFilter,includeMixed:e.target.checked})}/>양방향 공통 변화 포함</label></div>
 <div className="candidate-help"><p>보유 규모가 아닌 <b>주식 수량의 분기 증감</b>으로 선정합니다. 신규+확대 / 축소+청산을 각각 합산하며, 단순 유지 종목은 제외합니다. 양쪽 모두 최소 기준을 충족하면 의견 대립으로 표시합니다.</p><button className="text-button" onClick={onExportPolicy} disabled={!fundIds.length}>자동 조사 설정 내보내기 ↗</button></div>
 <details className="policy-note"><summary>후보 조건과 자동 조사 적용 방법</summary><p>화면과 TradingAgents 기반 배분안에 현재 조건을 적용합니다. 자동 분기 조사에도 적용하려면 내보낸 strategy.json을 pipeline/strategy.json으로 저장한 뒤 실행기를 재시작하세요. 이미 완료된 분기는 다시 거래하지 않습니다. 13F 수량 변화는 실제 거래 시점이나 현재 포지션을 뜻하지 않습니다.</p></details>
 {message&&<p role="status" aria-live="polite">{message}</p>}
 <div className="swing-list">{visible.map(row=>{const research=researchFor(row),moves=movementCounts(row);return <article className="panel swing-row" key={row.key}><div><h3>{row.ticker}</h3><p className="muted">{row.name}</p><span className="tag">{row.buyers>=candidateFilter.minFunds&&row.sellers>=candidateFilter.minFunds?'의견 대립 · ':''}{row.buyers>row.sellers?'확대 우세':row.sellers>row.buyers?'축소 우세':'의견 대립'}</span><div className="movement-grid"><span>신규 <b>{moves.new}</b></span><span>확대 <b>{moves.increased}</b></span><span>축소 <b>{moves.decreased}</b></span><span>청산 <b>{moves.closed}</b></span></div><p className="candidate-reason">{row.buyers>=candidateFilter.minFunds?`${row.buyers}개 펀드 공통 신규·확대`:""}{row.buyers>=candidateFilter.minFunds&&row.sellers>=candidateFilter.minFunds?" / ":""}{row.sellers>=candidateFilter.minFunds?`${row.sellers}개 펀드 공통 축소·청산`:""}</p></div><div className="swing-actions"><ResearchConclusion result={research} period={period}/>{research?.error&&<p role="alert">{research.error}</p>}<ResearchProgress result={research||{status:'completed'}}/>{research?.decision&&<button className="secondary-button" onClick={()=>onRead(row)}>보고서 전문 읽기</button>}<button className="primary-button" disabled={busy||['queued','running'].includes(research?.status||'')} onClick={()=>onResearch(row)}>리서치 실행 ↗</button><button className="text-button" onClick={()=>onEvidence(row)}>공시 근거</button><button className="secondary-button" onClick={()=>setChosen(row.key)}>{chosen===row.key?'기록할 종목 선택됨':'판단 기록'}</button></div></article>})}</div>
 {!rows.length&&<div className="panel empty">현재 후보 조건을 충족하는 종목이 없습니다. 방향·최소 펀드 수 또는 선택 펀드를 조정하세요.</div>}
 <nav className="pagination" aria-label="종목 리서치 페이지"><span>{rows.length}개 후보 · {current+1}/{pageCount}페이지</span><div><button disabled={current===0} onClick={()=>setPage(current-1)}>이전</button>{Array.from({length:pageCount},(_,i)=>i).filter(i=>i===0||i===pageCount-1||Math.abs(i-current)<=2).map((p,i,all)=><span key={p}>{i>0&&p-all[i-1]>1&&<span className="page-ellipsis">…</span>}<button aria-label={`${p+1}페이지`} aria-current={p===current?'page':undefined} onClick={()=>setPage(p)}>{p+1}</button></span>)}<button disabled={current===pageCount-1} onClick={()=>setPage(current+1)}>다음</button></div></nav>
 <div className="portfolio-grid"><section className="panel"><h2>판단 기록 {selected?`· ${selected.ticker}`:''}</h2><p className="muted">종목에서 ‘판단 기록’을 선택하세요. 작성 당시 가격과 공시·펀드 선택을 함께 보존합니다.</p><label className="field">관심을 갖는 이유<textarea value={thesis} onChange={e=>setThesis(e.target.value)} maxLength={3000}/></label><label className="field">확인할 촉매 / 진입 전 조건<textarea placeholder="예: 실적 발표 일정 확인 후, 가이던스가 유지되는지 확인" value={trigger} onChange={e=>setTrigger(e.target.value)} maxLength={3000}/></label><label className="field">판단을 철회할 조건<textarea value={invalid} onChange={e=>setInvalid(e.target.value)} maxLength={3000}/></label><label className="field">다음 점검일<input type="date" value={review} onChange={e=>setReview(e.target.value)}/></label><label className="field">현재 판단<select value={decision} onChange={e=>setDecision(e.target.value)}><option value="observe">관찰</option><option value="research">추가 조사</option><option value="skip">보류</option></select></label><button className="primary-button" disabled={!selected||!thesis.trim()||!trigger.trim()||!invalid.trim()||!review} onClick={save}>새 판단 기록 저장</button></section>
 <section className="panel"><h2>손실 예산으로 수량 검토</h2><p className="muted">직접 정한 가격의 매수 가정 계산입니다. 수수료·갭·슬리피지는 제외됩니다. 조정 종가는 주문 가격이 아닙니다.</p>{[['진입 가정 (USD)',entry,setEntry],['철회 가격 (USD)',stop,setStop],['목표 가정 (USD)',target,setTarget],['투입 상한 (USD)',budget,setBudget],['손실 예산 (USD)',risk,setRisk]].map(([title,value,setter])=><label className="field" key={title as string}>{title as string}<input type="number" min="0" step="any" value={value as string} onChange={e=>(setter as (v:string)=>void)(e.target.value)}/></label>)}{plan?<p>{plan.quantity}주 · 투입 ${number(plan.amount)} · 철회 가격 체결 가정 손실 ${number(plan.maxLoss)} · 손익비 {number(plan.rewardRisk)} : 1</p>:<p className="muted">0 &lt; 철회 가격 &lt; 진입 가격 &lt; 목표 가격, 손실 예산 ≤ 투입 상한으로 입력하세요.</p>}</section></div>
 <section className="panel methodology"><div className="section-heading"><h2>판단 일지 · {journal.length}건</h2><button className="secondary-button" onClick={exportJournal} disabled={!journal.length}>기록 내보내기</button></div><p className="muted">이 브라우저에만 저장됩니다. 실현 성과나 백테스트가 아닌 판단 이력입니다. 기한이 지난 기록은 재검토 후 새 기록을 남기세요.</p>{journal.slice(0,30).map(j=><details key={j.id} className="report-section"><summary>{j.ticker} · {j.review<=new Date().toLocaleDateString('en-CA')?'재검토 필요':'점검 예정'} {j.review} · {{observe:'관찰',research:'추가 조사',skip:'보류'}[j.decision]||j.decision}</summary><p>기록 {new Date(j.at).toLocaleString('ko-KR')} · 공시 {j.period}</p><p className="report-text">이유: {j.thesis}</p><p className="report-text">대기 조건: {j.trigger}</p><p className="report-text">철회 조건: {j.invalid}</p><p>연결 보고서 {j.researchAt||'미확인'}</p><button className="secondary-button" aria-label={`${j.ticker} 판단 기록 삭제`} onClick={()=>deleteEntry(j.id)}>이 기록 삭제</button></details>)}{journal.length>30&&<p>최근 30건 표시 · 전체 기록은 내보내기로 확인할 수 있습니다.</p>}</section></div>
}
