"use client";
import {useEffect,useState} from 'react';
import type {Aggregate} from '@/lib/domain';
import {reviewMarket,riskPlan,type MarketSnapshot} from '@/lib/swing';
import {ResearchProgress,ResearchConclusion,type Research} from './research-reader';
type Entry={id:string;at:string;ticker:string;period:string;fundIds:string[];thesis:string;trigger:string;invalid:string;review:string;decision:string;market?:MarketSnapshot;researchAt?:string};
const storageKey='hedge-swing-journal-v1';
const number=(v:number|undefined|null,suffix='')=>v==null?'—':v.toFixed(2)+suffix;
export function SwingWorkspace({rows,fundIds,period,researchFor,onResearch,onRead,onEvidence,busy}:{rows:Aggregate[];fundIds:string[];period:string;researchFor:(r:Aggregate)=>Research|undefined;onResearch:(r:Aggregate)=>void;onRead:(r:Aggregate)=>void;onEvidence:(r:Aggregate)=>void;busy:boolean}){
 const [page,setPage]=useState(0),[markets,setMarkets]=useState<Record<string,MarketSnapshot>>({}),[loading,setLoading]=useState(false),[message,setMessage]=useState('');
 const [chosen,setChosen]=useState(''),[journal,setJournal]=useState<Entry[]>([]),[thesis,setThesis]=useState(''),[trigger,setTrigger]=useState(''),[invalid,setInvalid]=useState(''),[review,setReview]=useState(''),[decision,setDecision]=useState('observe');
 const [entry,setEntry]=useState(''),[stop,setStop]=useState(''),[target,setTarget]=useState(''),[budget,setBudget]=useState('1000'),[risk,setRisk]=useState('10');
 const context=[...fundIds].sort().join(',')+'|'+period;
 useEffect(()=>{setPage(0);setChosen('');setMarkets({});setMessage('')},[context]);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(storageKey)||'[]');if(Array.isArray(saved)&&saved.every(e=>e&&typeof e.id==='string'&&typeof e.thesis==='string'&&typeof e.trigger==='string'&&typeof e.invalid==='string'&&typeof e.review==='string'&&typeof e.ticker==='string'&&typeof e.at==='string'))setJournal(saved);else setMessage('저장된 기록 형식을 읽을 수 없습니다.')}catch{setMessage('브라우저 기록을 읽지 못했습니다.')}},[]);
 const pageCount=Math.max(1,Math.ceil(rows.length/8)),current=Math.min(page,pageCount-1),visible=rows.slice(current*8,current*8+8),selected=rows.find(r=>r.key===chosen),plan=riskPlan(+entry,+stop,+target,+budget,+risk);
 async function refresh(){setLoading(true);setMessage('일별 가격을 확인하고 있습니다. 최대 8개 종목을 점검합니다.');try{const response=await fetch('/api/market',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({keys:visible.map(r=>r.key),fundIds})});const result=await response.json() as {error?:string;rows:MarketSnapshot[]};if(!response.ok)throw Error(result.error||'가격 점검 실패');setMarkets(old=>({...old,...Object.fromEntries(result.rows.map((r:MarketSnapshot)=>[r.key,r]))}));setMessage('가격 점검 완료 · AI 호출 0회. 확인 불가 항목은 각 종목에 표시합니다.')}catch(e){setMessage(e instanceof Error?e.message:'가격 점검 실패')}finally{setLoading(false)}}
 function save(){if(!selected||!thesis.trim()||!trigger.trim()||!invalid.trim()||!review)return;const item:Entry={id:crypto.randomUUID(),at:new Date().toISOString(),ticker:selected.ticker!,period,fundIds:[...fundIds],thesis,trigger,invalid,review,decision,market:markets[selected.key],researchAt:researchFor(selected)?.createdAt};const next=[item,...journal];try{localStorage.setItem(storageKey,JSON.stringify(next));setJournal(next);setMessage('판단 시점의 근거를 기록했습니다.');setThesis('');setTrigger('');setInvalid('')}catch{setMessage('저장 공간 또는 브라우저 권한 문제로 기록을 저장하지 못했습니다.')}}
 function exportJournal(){const url=URL.createObjectURL(new Blob([JSON.stringify({schemaVersion:1,entries:journal},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='swing-journal.json';a.click();URL.revokeObjectURL(url)}
 return <div className="swing-workspace"><div className="section-heading spacious"><div><p className="eyebrow">2–6 WEEK SWING WORKSPACE</p><h2>후보 점검부터 AI 결론까지</h2><p className="muted">공통 매매 → 가격 점검 → 필요한 AI 조사 → 조건 기록 → 예정일에 재검토</p></div><button className="primary-button" disabled={loading||!visible.length} onClick={refresh}>{loading?'가격 확인 중…':'현재 페이지 가격 점검'}</button></div>
 <div className="notice">공시 기준 {period} · 분기 말부터 {Math.max(0,Math.floor((Date.now()-Date.parse(period))/86400000))}일 경과. 13F는 분기 말 보유 수량을 보여주므로 최근 매매 시점을 알 수 없습니다. 아래 상태는 조사 순서를 돕는 관찰 규칙입니다.</div>
 <div className="notice">같은 방향으로 수량을 바꾼 펀드가 2개 이상인 후보만 조사합니다. 공통 방향 펀드 수, 방향 일치율 순이며 같은 티커는 한 번만 표시합니다. 페이지 이동은 AI를 실행하지 않습니다.</div>
 <p role="status" aria-live="polite">{message||'가격 점검은 AI 비용 없이 실행하며, 서버에서 4시간 동안 재사용합니다.'}</p>
 <div className="swing-list">{visible.map(row=>{const market=markets[row.key],research=researchFor(row);return <article className="panel swing-row" key={row.key}><div><h3>{row.ticker}</h3><p className="muted">{row.name}</p><span className="tag">{reviewMarket(row.buyers,row.sellers,market)}</span><p>확대 {row.buyers} · 축소 {row.sellers}</p></div><div><p>조정 종가 <b>{number(market?.close)}</b> USD</p><p>20 / 50일 평균 {number(market?.sma20)} / {number(market?.sma50)}</p><p>20거래일 수익률 {number(market?.return20==null?null:market.return20*100,'%')} · SPY 대비 {number(market?.relativeReturn20==null?null:market.relativeReturn20*100,'%p')}</p><p>거래량 / 직전 20일 평균 {number(market?.relativeVolume,'배')}</p>{market?.asOf&&<a href={market.sourceUrl} target="_blank" rel="noreferrer">가격 기준 {market.asOf} ↗</a>}{market?.dataGaps.map(g=><p className="negative" key={g}>{g}</p>)}</div><div className="swing-actions"><ResearchConclusion result={research} period={period}/>{research?.error&&<p role="alert">{research.error}</p>}<ResearchProgress result={research||{status:'completed'}}/>{research?.decision&&<button className="secondary-button" onClick={()=>onRead(row)}>보고서 전문 읽기</button>}<button className="primary-button" disabled={busy||['queued','running'].includes(research?.status||'')} onClick={()=>onResearch(row)}>AI 조사 / 오늘 결과 확인</button><button className="text-button" onClick={()=>onEvidence(row)}>공시 근거</button><button className="secondary-button" onClick={()=>setChosen(row.key)}>{chosen===row.key?'기록할 종목 선택됨':'판단 기록'}</button></div></article>})}</div>
 {!rows.length&&<div className="panel empty">같은 방향의 매매가 2개 이상 펀드에서 확인된 종목이 없습니다. 펀드 선택을 확인하세요.</div>}
 <nav className="pagination" aria-label="종목 리서치 페이지"><span>{rows.length}개 후보 · {current+1}/{pageCount}페이지</span><div><button disabled={current===0||loading} onClick={()=>setPage(current-1)}>이전</button>{Array.from({length:pageCount},(_,i)=>i).filter(i=>i===0||i===pageCount-1||Math.abs(i-current)<=2).map((p,i,all)=><span key={p}>{i>0&&p-all[i-1]>1&&<span className="page-ellipsis">…</span>}<button disabled={loading} aria-label={`${p+1}페이지`} aria-current={p===current?'page':undefined} onClick={()=>setPage(p)}>{p+1}</button></span>)}<button disabled={current===pageCount-1||loading} onClick={()=>setPage(current+1)}>다음</button></div></nav>
 <div className="portfolio-grid"><section className="panel"><h2>판단 기록 {selected?`· ${selected.ticker}`:''}</h2><p className="muted">종목에서 ‘판단 기록’을 선택하세요. 작성 당시 가격과 공시·펀드 선택을 함께 보존합니다.</p><label className="field">관심을 갖는 이유<textarea value={thesis} onChange={e=>setThesis(e.target.value)} maxLength={3000}/></label><label className="field">확인할 촉매 / 진입 전 조건<textarea placeholder="예: 실적 발표 일정 확인 후, 가이던스가 유지되는지 확인" value={trigger} onChange={e=>setTrigger(e.target.value)} maxLength={3000}/></label><label className="field">판단을 철회할 조건<textarea value={invalid} onChange={e=>setInvalid(e.target.value)} maxLength={3000}/></label><label className="field">다음 점검일<input type="date" value={review} onChange={e=>setReview(e.target.value)}/></label><label className="field">현재 판단<select value={decision} onChange={e=>setDecision(e.target.value)}><option value="observe">관찰</option><option value="research">추가 조사</option><option value="skip">보류</option></select></label><button className="primary-button" disabled={!selected||!thesis.trim()||!trigger.trim()||!invalid.trim()||!review} onClick={save}>새 판단 기록 저장</button></section>
 <section className="panel"><h2>손실 예산으로 수량 검토</h2><p className="muted">직접 정한 가격의 매수 가정 계산입니다. 수수료·갭·슬리피지는 제외됩니다. 조정 종가는 주문 가격이 아닙니다.</p>{[['진입 가정 (USD)',entry,setEntry],['철회 가격 (USD)',stop,setStop],['목표 가정 (USD)',target,setTarget],['투입 상한 (USD)',budget,setBudget],['손실 예산 (USD)',risk,setRisk]].map(([title,value,setter])=><label className="field" key={title as string}>{title as string}<input type="number" min="0" step="any" value={value as string} onChange={e=>(setter as (v:string)=>void)(e.target.value)}/></label>)}{plan?<p>{plan.quantity}주 · 투입 ${number(plan.amount)} · 철회 가격 체결 가정 손실 ${number(plan.maxLoss)} · 손익비 {number(plan.rewardRisk)} : 1</p>:<p className="muted">0 &lt; 철회 가격 &lt; 진입 가격 &lt; 목표 가격, 손실 예산 ≤ 투입 상한으로 입력하세요.</p>}</section></div>
 <section className="panel methodology"><div className="section-heading"><h2>판단 일지 · {journal.length}건</h2><button className="secondary-button" onClick={exportJournal} disabled={!journal.length}>기록 내보내기</button></div><p className="muted">이 브라우저에만 저장됩니다. 실현 성과나 백테스트가 아닌 판단 이력입니다. 기한이 지난 기록은 재검토 후 새 기록을 남기세요.</p>{journal.slice(0,30).map(j=><details key={j.id} className="report-section"><summary>{j.ticker} · {j.review<=new Date().toLocaleDateString('en-CA')?'재검토 필요':'점검 예정'} {j.review} · {{observe:'관찰',research:'추가 조사',skip:'보류'}[j.decision]||j.decision}</summary><p>기록 {new Date(j.at).toLocaleString('ko-KR')} · 공시 {j.period}</p><p className="report-text">이유: {j.thesis}</p><p className="report-text">대기 조건: {j.trigger}</p><p className="report-text">철회 조건: {j.invalid}</p><p>당시 가격 {number(j.market?.close)} · 기준 {j.market?.asOf||'미확인'} · 보고서 {j.researchAt||'미확인'}</p></details>)}{journal.length>30&&<p>최근 30건 표시 · 전체 기록은 내보내기로 확인할 수 있습니다.</p>}</section>
 <details className="panel methodology"><summary>가격 점검 기준과 해석</summary><p>매수 우세이며 조정 종가가 20·50거래일 단순이동평균보다 높고, 같은 20거래일의 수익률이 SPY보다 높으면 ‘추세 확인 · 촉매 조사’로 표시합니다. 충족하지 않으면 가격 흐름 대기입니다. 매도 우세는 위험 점검용입니다.</p><p>거래량 배수는 최근 거래일 거래량 ÷ 그 전 20거래일 평균입니다. 뉴욕 기준 당일 봉은 완료 여부와 관계없이 제외합니다. 가격이 5일을 초과해 오래되거나 USD·SPY 근거가 없으면 데이터 재확인으로 표시합니다. 이 임계값은 검증된 수익 예측 공식이 아닙니다.</p></details></div>
}
