export const fundPeople:Record<string,{name:string;role:string}>={
 situational:{name:'Leopold Aschenbrenner',role:'창립자 · CIO'},
 berkshire:{name:'Warren Buffett',role:'회장'},
 duquesne:{name:'Stanley Druckenmiller',role:'창립자'},
 pershing:{name:'Bill Ackman',role:'창립자 · CEO'},
 bridgewater:{name:'Ray Dalio',role:'창립자'},
 renaissance:{name:'Jim Simons',role:'창립자'},
 blackrock:{name:'Larry Fink',role:'공동창립자 · 회장'},
 altimeter:{name:'Brad Gerstner',role:'창립자 · CEO'},
 tci:{name:'Chris Hohn',role:'창립자'},
 appaloosa:{name:'David Tepper',role:'창립자'},
 tudor:{name:'Paul Tudor Jones',role:'창립자'},
 citadel:{name:'Ken Griffin',role:'창립자 · CEO'},
 himalaya:{name:'Li Lu',role:'창립자 · 회장'},
 ark:{name:'Cathie Wood',role:'창립자 · CEO · CIO'},
 janestreet:{name:'Tim Reynolds',role:'공동창립자'},
 nvidia:{name:'Jensen Huang',role:'공동창립자 · CEO'},
 oaktree:{name:'Howard Marks',role:'공동창립자 · 공동회장'},
 point72:{name:'Steve Cohen',role:'창립자'},
 coatue:{name:'Philippe Laffont',role:'창립자'},
 dalal:{name:'Mohnish Pabrai',role:'CEO · 펀드매니저'},
 thirdpoint:{name:'Daniel Loeb',role:'창립자 · CEO'},
 viking:{name:'Andreas Halvorsen',role:'공동창립자 · CEO'},
 lonepine:{name:'Steve Mandel',role:'창립자'}
};
